// Generated by https://quicktype.io

export interface IFoodSearch {
  foods: Foods;
}

export interface Foods {
  food: Food[];
  max_results: number;
  page_number: number;
  total_results: number;
}

export interface Food {
  food_description: string;
  food_id: number;
  food_name: string;
  food_type: string;
  food_url: string;
  brand_name?: string;
}
