// Generated by https://quicktype.io

export interface IFoodSearch {
  foods: Foods;
}

export interface Foods {
  food: Food[];
  max_results: string;
  page_number: string;
  total_results: number;
}

export interface Food {
  food_description: string;
  food_id: string;
  food_name: string;
  food_type: string;
  food_url: string;
  brand_name?: string;
}

// Generated by https://quicktype.io

export interface IFood {
  food: Food;
}

export interface Food {
  food_id: string;
  food_name: string;
  food_type: string;
  food_url: string;
  servings: Servings;
}

export interface Servings {
  serving: { [key: string]: string }[];
}
